name: 'jenkins-server'

services:
  jenkins:
    image: jenkins/jenkins:lts
    build:
     context: .
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ~/jenkins-home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

  # Optional: Docker-in-Docker service, not required if mounting docker.sock
  # dind:
  #   image: docker:dind
  #   container_name: jenkins-dind
  #   privileged: true
  #   networks:
  #     - jenkins

# volumes:
#   jenkins_home:
#     driver: local
#     driver_opts: 
#       type: none
#       o: bind
#       device: ~/jenkins-home/

networks:
  jenkins:
    driver: bridge

