apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server-deployment
  labels:
    app: simple-server
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
      - name: simple-server
        image: andreimihai/simple-server:0.1.0
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-server
  name: simple-server
spec:
  ports:
  - port: 8123
    name: port-simple-server
    protocol: TCP
    targetPort: 8123
  selector:
    app: simple-server