apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: socialmedia
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: site
  name: site
  namespace: socialmedia
spec:
  containers:
  - image: nginx
    name: site
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
